import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./page.module.css";
import CartProvider from "./context/CartProvider";
import TopNav from "./ui/TopNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Quality Items</title>
      </head>
      <body>
        <CartProvider>
          <TopNav />
          
          {children}
        </CartProvider>
        </body>
    </html>
  );
}
